#!/usr/bin/env bash
# Provision a musl-targeting C toolchain for the *-unknown-linux-musl release
# builds.
#
# Why this exists
# ---------------
# Rust's musl targets ship their own libc, but any dependency that compiles C
# through cc-rs needs a C compiler that actually targets musl. Karvex has no
# such dependency today, but this keeps the release legs working the moment one
# is added. The GitHub Linux runners have no
# aarch64 musl compiler at all, and on the aarch64 leg the situation is worse:
# the workflow sets CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER, cargo
# exports it to build scripts as RUSTC_LINKER, and cc-rs derives its tool
# prefix from RUSTC_LINKER *before* consulting its own musl table. cc-rs
# therefore compiles with the glibc cross compiler, and the resulting objects
# fail to link against musl with undefined references to glibc-only symbols
# (`__fprintf_chk`, `__isoc23_sscanf`, ...).
#
# Zig is already installed for the vendored libghostty-vt build and `zig cc`
# targets musl natively for both architectures, so use it as the C compiler and
# archiver. An explicit CC_<target>/AR_<target> outranks every prefix inference
# in cc-rs, which also neutralises the RUSTC_LINKER leak. The final Rust link
# step is deliberately left alone.
#
# Usage
# -----
#   scripts/setup_musl_cc.sh <rust-target> <bin-dir>
#
# Writes wrapper executables into <bin-dir> and prints the resulting
# environment assignments to stdout, ready to append to "$GITHUB_ENV" or to be
# exported locally. Targets that are not linux-musl are a no-op, so callers can
# run this unconditionally for every entry in a release matrix.
set -euo pipefail

usage() {
  echo "usage: scripts/setup_musl_cc.sh <rust-target> <bin-dir>" >&2
  exit 2
}

[[ $# -eq 2 ]] || usage
TARGET=$1
BIN_DIR=$2
[[ -n "$TARGET" && -n "$BIN_DIR" ]] || usage

case "$TARGET" in
  x86_64-unknown-linux-musl) ZIG_TARGET=x86_64-linux-musl ;;
  aarch64-unknown-linux-musl) ZIG_TARGET=aarch64-linux-musl ;;
  *) exit 0 ;;
esac

mkdir -p "$BIN_DIR"
BIN_DIR=$(cd -- "$BIN_DIR" && pwd)

CC_PATH="$BIN_DIR/$TARGET-zig-cc"
AR_PATH="$BIN_DIR/$TARGET-zig-ar"
RANLIB_PATH="$BIN_DIR/$TARGET-zig-ranlib"

{
  printf '#!/usr/bin/env bash\n'
  printf '# Generated by scripts/setup_musl_cc.sh - do not edit.\n'
  printf 'ZIG_TARGET=%s\n' "$ZIG_TARGET"
  cat <<'SHIM'
set -euo pipefail
# cc-rs identifies `zig cc` as clang and appends the full four-field Rust
# triple as `--target=<arch>-unknown-linux-musl`. Zig parses target queries as
# <arch>-<os>-<abi>, so that triple is rejected outright
# ("UnknownOperatingSystem"). Drop any caller-supplied target and pin the zig
# one instead.
args=()
skip=0
for arg in "$@"; do
  if [[ $skip -eq 1 ]]; then
    skip=0
    continue
  fi
  case "$arg" in
    --target=*) continue ;;
    -target) skip=1 ;;
    *) args+=("$arg") ;;
  esac
done
exec "${ZIG:-zig}" cc -target "$ZIG_TARGET" ${args[@]+"${args[@]}"}
SHIM
} >"$CC_PATH"

{
  printf '#!/usr/bin/env bash\n'
  printf '# Generated by scripts/setup_musl_cc.sh - do not edit.\n'
  printf 'set -euo pipefail\n'
  printf 'exec "${ZIG:-zig}" ar "$@"\n'
} >"$AR_PATH"

{
  printf '#!/usr/bin/env bash\n'
  printf '# Generated by scripts/setup_musl_cc.sh - do not edit.\n'
  printf 'set -euo pipefail\n'
  printf 'exec "${ZIG:-zig}" ranlib "$@"\n'
} >"$RANLIB_PATH"

chmod +x "$CC_PATH" "$AR_PATH" "$RANLIB_PATH"

# cc-rs looks the underscored form up first, and it is the only form that is a
# valid shell identifier, so it is also what works when exported directly.
ENV_TARGET=${TARGET//-/_}
printf 'CC_%s=%s\n' "$ENV_TARGET" "$CC_PATH"
printf 'AR_%s=%s\n' "$ENV_TARGET" "$AR_PATH"
printf 'RANLIB_%s=%s\n' "$ENV_TARGET" "$RANLIB_PATH"
